import React, {useEffect, useMemo, useState} from "react";
import {createRoot} from "react-dom/client";
import {Heart, Sparkles, CalendarDays, Music2, ChevronDown, LockKeyhole, Gift, Play, Pause, Shuffle, MapPin, Send, Mail} from "lucide-react";
import {couple, timeline, memories, reasons, dateIdeas, insideJokes} from "./data";
import GamesHub from "./games/GamesHub";
import "./styles.css";

const photos = ["PHOTO 01","PHOTO 02","PHOTO 03","PHOTO 04"];
// Toutou's WhatsApp number (digits only, with country code, no + or leading 0)
const WHATSAPP_NUMBER = "21623897700";

function Countdown(){
  const [now,setNow]=useState(Date.now());
  useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
  const diff=Math.max(0,new Date(couple.nextDate).getTime()-now);
  const d=Math.floor(diff/86400000), h=Math.floor(diff/3600000)%24, m=Math.floor(diff/60000)%60, s=Math.floor(diff/1000)%60;
  return <div className="countdown"><div><b>{String(d).padStart(2,"0")}</b><span>days</span></div><i>:</i><div><b>{String(h).padStart(2,"0")}</b><span>hours</span></div><i>:</i><div><b>{String(m).padStart(2,"0")}</b><span>min</span></div><i>:</i><div><b>{String(s).padStart(2,"0")}</b><span>sec</span></div></div>
}

function App(){
 const [hugging,setHugging]=useState(false), [entered,setEntered]=useState(false), [secret,setSecret]=useState(false), [letter,setLetter]=useState(false), [music,setMusic]=useState(false), [date,setDate]=useState(dateIdeas[0]), [toast,setToast]=useState("");
 const [menu,setMenu]=useState(false);
 const [message,setMessage]=useState("");
 const [quiz,setQuiz]=useState(0),[quizDone,setQuizDone]=useState(false),[bouquet,setBouquet]=useState(false),[openWhen,setOpenWhen]=useState<[string,string]|null>(null),[checked,setChecked]=useState<number[]>([]),[reason,setReason]=useState(0);
 const sendMessage=()=>{if(!message.trim())return;const text=encodeURIComponent(`💌 A message from Loudy:\n\n${message.trim()}`);window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${text}`,"_blank");setMessage("");setToast("Opening WhatsApp so you can send it to Toutou ❤️");setTimeout(()=>setToast(""),4000)};
 const randomDate=()=>setDate(dateIdeas[Math.floor(Math.random()*dateIdeas.length)]);
 const surprise=()=>{setSecret(true);setTimeout(()=>setSecret(false),8000)};
 const toggleTask=(i)=>setChecked(x=>x.includes(i)?x.filter(v=>v!==i):[...x,i]);
 const reminder=()=>{const msgs=["Loudy, you're still Toutou's favorite person. ❤️","Just in case you forgot: you're loved.","Reminder: Toutou is thinking about you.","You + Me = my favorite story.","One more reason to smile: someone is thinking about you."]; setToast(msgs[Math.floor(Math.random()*msgs.length)]); setTimeout(()=>setToast(""),3500)};
 if(!entered) return <div className="letter-gate"><div className="letter-glow"/><div className="letter-paper"><div className="letter-seal">L <span>×</span> T</div><span className="letter-small">A private letter for</span><h1>My Loudy,</h1><p className="letter-intro">I made this little place<br/>for the girl who has my favorite eyes.</p><div className="letter-line"/><p className="letter-body">There are memories we have already made,<br/>and so many more waiting for us.</p><button onClick={()=>setEntered(true)}>Open our little universe <Heart size={17} fill="currentColor"/></button><span className="letter-sign">Love, Toutou</span></div></div>

 return <div className="app">
  <div className="ambient"/>
  <nav><a className="brand" href="#home">L<span>×</span>T</a><div className={"links "+(menu?"open":"")}><a href="#story" onClick={()=>setMenu(false)}>Our Story</a><a href="#memories" onClick={()=>setMenu(false)}>Memories</a><a href="#dates" onClick={()=>setMenu(false)}>Dates</a><a href="#games" onClick={()=>setMenu(false)}>Games</a><a href="#polaroids" onClick={()=>setMenu(false)}>Polaroids</a><a href="#letter" onClick={()=>setMenu(false)}>Letter</a></div><button className="menu" onClick={()=>setMenu(!menu)}>{menu?"×":"☰"}</button></nav>

  <main>
   <section id="home" className="hero"><div className="eyebrow"><Sparkles size={15}/> OUR LITTLE UNIVERSE</div><h1>Welcome to the world of<br/><em>Loudy & Toutou</em> <Heart fill="currentColor"/></h1><p>Two people. One story. A thousand little moments.</p><div className="photo-note"><Heart size={13} fill="currentColor"/> A little world made by Toutou for Loudy</div><a className="primary" href="#story">Start Our Story <ChevronDown size={18}/></a><div className="orb"><span>∞</span></div></section>

   <section id="story" className="section"><div className="section-head"><span>01</span><h2>How It All Started</h2><p>From a music exhibition to 04/07/2026 — the day our conversations became deeper.</p></div><div className="timeline">{timeline.map((x,i)=><article className="timeline-item" key={i}><div className="dot"/><div className="date">{x.date}</div><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></section>

   <section id="memories" className="section"><div className="section-head"><span>02</span><h2>Little Moments, Big Memories</h2><p>These are AI-made memories for now. Our first real photo is still waiting to happen.</p></div><div className="gallery">{memories.map((m,i)=><article className="memory" key={i}><div className={"photo p"+i}>{i < 2 ? <img src={`/photos/loudy-toutou-0${i+1}.png`} alt={`Loudy and Toutou memory ${i+1}`} /> : <div><span>{photos[i]}</span><small>{i < 2 ? "AI-made memory" : "Our future real photo"}</small></div>}</div><div className="memory-copy"><span>MEMORY 0{i+1}</span><h3>{m[0]}</h3><p>{m[1]}</p></div></article>)}</div></section>

   <section className="section dark"><div className="section-head"><span>03</span><h2>Why I Love My Loudy</h2><p>Click a card. There are more reasons than these.</p></div><div className="reasons">{reasons.map((r,i)=><div className="reason" key={i}><div className="number">0{i+1}</div><Heart size={18}/><h3>{r[0]}</h3><p>{r[1]}</p></div>)}</div></section>

   <section id="dates" className="section date-section"><div className="section-head"><span>04</span><h2>Our Little Dates</h2><p>We still haven’t had our first date. Let’s make it one of our next chapters.</p></div><div className="date-layout"><div className="date-card"><div className="date-icon"><CalendarDays/></div><span>NEXT DATE IDEA</span><h3>{date}</h3><button className="secondary" onClick={randomDate}><Shuffle size={16}/> Give us another idea</button></div><div className="date-list">{dateIdeas.slice(0,6).map((x,i)=><div className="date-row" key={i}><span>0{i+1}</span><p>{x}</p><MapPin size={15}/></div>)}</div></div></section>

   <section className="section calendar"><div className="calendar-card"><div><span className="eyebrow">OUR SPECIAL DATES</span><h2>More chapters to come.</h2><p>Add your real anniversary, first meeting, birthdays and every date that matters to you in <code>src/data.ts</code>.</p></div><div className="count-wrap"><small>COUNTING DOWN TO YOUR NEXT SPECIAL DAY</small><Countdown/></div></div></section>

   <section className="section dark"><div className="section-head"><span>05</span><h2>Things That Are Very Us</h2><p>The little things only Loudy & Toutou understand.</p></div><div className="jokes">{insideJokes.map((x,i)=><details key={i}><summary>{x[0]} <ChevronDown/></summary><p>{x[1]}</p></details>)}</div></section>

   <section className="section interactive-section"><div className="section-head"><span>06</span><h2>Little Things For Us</h2><p>Some tiny surprises, questions, and promises made just for Loudy & Toutou.</p></div><div className="feature-grid"><div className="feature-card"><Gift/><h3>Virtual Bouquet</h3><p>A little bouquet, whenever you need one.</p><button className="secondary" onClick={()=>setBouquet(true)}>Send flowers 🌹</button></div><div className="feature-card"><Heart/><h3>One More Reason</h3><p>{reasons[reason][1]}</p><button className="secondary" onClick={()=>setReason((reason+1)%reasons.length)}>Another reason</button></div></div><div className="open-when"><h3>Open when...</h3><div className="feature-grid">{[["You miss me","I am closer than you think. Close your eyes, smile, and remember that you are my favorite place."],["You feel sad","You do not have to be strong every second. Take a breath. I am always cheering for you."],["You need a smile","Your smile is my favorite little miracle. Now go make the world brighter."],["We have a silly fight","We are on the same team. Let us choose kindness, then laugh about it later."]].map((x,i)=><button className="letter-chip" key={i} onClick={()=>setOpenWhen(x)}><span>💌</span>{x[0]}</button>)}</div></div><div className="bucket"><h3>Our Couple Bucket List</h3>{["Take our first real photo together","Watch a sunrise together","Cook something together","Travel somewhere new","Make a playlist for us","Write a time capsule"].map((x,i)=><label key={i} className={checked.includes(i)?"task done":"task"}><input type="checkbox" checked={checked.includes(i)} onChange={()=>toggleTask(i)}/>{x}</label>)}</div><div className="quiz"><h3>How well do you know us?</h3>{!quizDone?<><p>{[["Who deserves the biggest hug?",["Loudy","Toutou","Both"]],["What should our next chapter include?",["A real date","More memories","All of it"]],["What is our secret superpower?",["Laughing together","Understanding each other","Being us"]]][quiz][0]}</p><div className="answers">{[["Loudy","Toutou","Both"],["A real date","More memories","All of it"],["Laughing together","Understanding each other","Being us"]][quiz].map((x,i)=><button key={i} onClick={()=>quiz<2?setQuiz(quiz+1):setQuizDone(true)}>{x}</button>)}</div></>:<h3>Perfect match. You are our favorite story. ❤️</h3>}</div></section>

   <GamesHub/>

   <section id="polaroids" className="section polaroid-section"><div className="section-head"><span>08</span><h2>Our Little Polaroid Wall</h2><p>Small snapshots of a story that keeps becoming more beautiful.</p></div><div className="polaroid-wall">{[1,2,3,4].map((n,i)=><article className="polaroid" key={n}>{i<2?<img src={`/photos/loudy-toutou-0${n}.png`} alt={`Loudy and Toutou polaroid ${n}`}/>:<div className="polaroid-placeholder">Our next<br/>memory ❤️</div>}<small>{["A little moment","My favorite smile","Soon to be real","More us, always"][i]}</small></article>)}</div></section><section className="hug-section"><div className={"hug-card "+(hugging?"hugging":"")}><div className="hug-heart">🤗</div><h2>Send a Virtual Hug</h2><p>Whenever Toutou needs a hug, Loudy can send one from anywhere.</p><button className="hug-button" onClick={()=>{setHugging(true);setToast("A warm hug was sent to Toutou ❤️");setTimeout(()=>setHugging(false),1600);setTimeout(()=>setToast(""),4000)}}><Heart size={17} fill="currentColor"/> Send me a hug</button></div></section><section id="one-minute" className="section minute-section"><div className="section-head"><span>09</span><h2>One Minute Together</h2><p>A tiny activity to make one quiet minute feel like ours.</p></div><div className="minute-card"><div className="minute-timer">60</div><h3>Take one minute for us.</h3><p>Put your phone down, breathe slowly, and think of one beautiful thing about Toutou.</p><button className="primary" onClick={()=>{setToast("One beautiful minute together starts now ❤️");setTimeout(()=>setToast(""),4000)}}>Start our minute <Heart size={16} fill="currentColor"/></button></div></section><section id="envelopes" className="section envelope-wall-section"><div className="section-head"><span>10</span><h2>Our Secret Envelope Wall</h2><p>Choose an envelope and open a little message made with love.</p></div><div className="envelope-wall">{[["When you miss me","Even when we are far apart, you are always close to my heart. ❤️"],["When you need courage","You can do difficult things. I believe in you, always."],["When you need a smile","Your smile is my favorite notification."],["When you want a surprise","Your next beautiful memory is still waiting for us."]].map((x,i)=><button className="wall-envelope" key={i} onClick={()=>setOpenWhen(x)}><span>✉️</span><b>{x[0]}</b><small>Click to open</small></button>)}</div></section><section id="letter" className="letter-section"><div className="envelope-wrap"><div className={"envelope "+(letter?"open":"")} onClick={()=>setLetter(true)}><div className="env-top"/><div className="paper"><span>My Loudy,</span><p>There are some things that deserve more than a text.</p><b>Open me ❤️</b></div><div className="env-bottom"/></div><div className="letter-title"><span>11</span><h2>A Letter From Toutou</h2><p>Click the envelope.</p></div></div></section>

   <section className="section daily"><div className="daily-card"><span>DAILY REMINDER</span><h2>You are loved, today and every day. ❤️</h2><button className="secondary" onClick={reminder}>Give me another reminder</button></div></section>
   <section id="message" className="section message-section"><div className="section-head"><span>12</span><h2>Tell Toutou Anything</h2><p>A private little place for every thought, feeling, story, or random message.</p></div><div className="message-card"><div className="message-top"><div className="message-icon"><Mail/></div><div><span>FROM LOUDY TO TOUTOU</span><h3>Write whatever is on your heart.</h3></div></div><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Hey Toutou… I wanted to tell you something..." rows={7}/><div className="message-bottom"><small><Heart size={13} fill="currentColor"/> This opens WhatsApp with your message ready to send to Toutou.</small><button className="primary" onClick={sendMessage} disabled={!message.trim()}>Send to Toutou <Send size={16}/></button></div></div></section>

   <section className="secret-section"><LockKeyhole/><h2>A little secret...</h2><p>Only Loudy should open this.</p><button className="primary" onClick={surprise}>Don't Click This ❤️</button></section>

   <section className="final"><div className="final-stars">✦　·　✧　·　✦</div><p>Loudy...</p><h2>I'd still choose you.</h2><h3>Every time.</h3><div className="signature">Loudy <span>♥</span> Toutou</div><small>Our story is still being written...<br/>To be continued.</small></section>
  </main>

  <button className={"music "+(music?"playing":"")} onClick={()=>setMusic(!music)} title="Music"><Music2 size={18}/>{music?<Pause size={14}/>:<Play size={14}/>}</button>
  <button className="reminder" onClick={reminder}><Gift size={18}/></button>
  {toast&&<div className="toast">{toast}</div>}{bouquet&&<div className="overlay" onClick={()=>setBouquet(false)}><div className="surprise"><div className="bouquet">🌹🌷🌹</div><h2>A bouquet for you, Loudy.</h2><p>Every flower carries a little piece of my love.</p></div></div>}{openWhen&&<div className="overlay" onClick={()=>setOpenWhen(null)}><div className="full-letter" onClick={e=>e.stopPropagation()}><button onClick={()=>setOpenWhen(null)}>×</button><span>OPEN WHEN...</span><h2>{openWhen[0]}</h2><p>{openWhen[1]}</p><h3>Always yours,<br/>Toutou ❤️</h3></div></div>}
  {secret&&<div className="overlay"><div className="surprise"><Sparkles/><p>Okay Loudy...<br/>you clicked it. 😌</p><h2>I love you more than this website could ever explain.</h2><span>Now come here. ❤️</span></div></div>}
  {letter&&<div className="overlay" onClick={()=>setLetter(false)}><div className="full-letter" onClick={e=>e.stopPropagation()}><button onClick={()=>setLetter(false)}>×</button><span>A LETTER FROM TOUTOU</span><h2>My Loudy,</h2><p>I don't think I'll ever find enough words to explain what you mean to me.</p><p>But I know that every little moment with you became something I want to remember.</p><p>The dates. The laughs. The arguments. The stupid conversations. The quiet moments.</p><p>All of it.</p><p>You became one of my favorite parts of life.</p><p>And if our story is a book, I don't want to finish it.</p><p>I want more chapters.<br/>More memories.<br/>More adventures.<br/>More dates.<br/><b>More us.</b></p><h3>Always yours,<br/>Toutou ❤️</h3></div></div>}
 </div>
}

createRoot(document.getElementById("root")!).render(<App/>);
